### ISSUE TITLE
How to decide the parameter in yml file?

### ISSUE THREAD

**Issue by Yamameeee** [tteepe/TrackTacular#1]
Than you for sharing your great work and implementation!
I have some quenstions.
How to decide `zmax in bounds`, `Z in resolution` and `z_sign` in data yml file?
(e.g., `bounds: [0, 1000, 0, 640, 0, **2**] `, `z_sign: **-1**` in `d_multiviewx.yml`)

**Comment by tteepe** [comment]
Hi,

- `zmax` comes from the assumption that most people are maximum 2m tall.
- `z_sign` is the direction of the camera z axes, you can try experimentally 
-  `Z` resolution you can choose freely, our experiments showed that 2 is a good value

Hope this helps!
Torben

**Comment by Yamameeee** [comment]
Thanks for your reply.
I understand why `zmax` is `2` in `d_multiviewz.yml` and `d_synthehicle.yml`.
Why  `zmax` is `200` in `d_wildtrack.yml`?

**Comment by tteepe** [comment]
wildtrack is calibrated in `cm`, the others are in meters.

**Comment by Yamameeee** [comment]
Got it. Thank you!
